#!/usr/bin/env python
"""Panel-match Part 1 — go/no-go: overlap of candidate imcdatasets panels vs Moldoveanu.

Same Jaccard method as src/check_marker_overlap.py, applied to each candidate panel, plus an
explicit named check for the 4 checkpoint/exhaustion markers (PD1, LAG3, TIM3, granzyme) in
BOTH panels. Bar: best candidate needs Jaccard >= 40% AND >= 2/4 checkpoint markers shared.
Writes ranked results to docs/panel_matched_candidates.md and prints the go/no-go verdict.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from utils import REPO

THRESHOLD_JACCARD = 40.0     # percent — must be clearly above the 11.5% Jackson overlap
THRESHOLD_CHECKPOINTS = 2    # of 4

# transparent synonym map (canonical protein), committed before seeing the result.
# strip punctuation/case first, then apply. Only same-protein clone/name variants.
SYN = {
    "cd3e": "cd3",
    "histoneh3": "h3", "histone": "h3",
    "cd8a": "cd8",
    "granzymeb": "gzmb", "grzb": "gzmb", "granzyme": "gzmb", "gzmb": "gzmb",
    "pd1": "pd1", "pdcd1": "pd1",
    "pdl1": "pdl1",
    "cd134": "ox40", "tnfrsf4": "ox40",
    "ecad": "cdh1", "ecadherin": "cdh1",
    "bcatenin": "ctnnb", "betacatenin": "ctnnb",
    "mart1": "mlana", "mela": "mlana",
    "lag33": "lag3",
}

CHECKPOINTS = {            # canonical -> display; membership tested on normalized names
    "pd1": "PD1", "lag3": "LAG3", "tim3": "TIM3", "gzmb": "granzyme(GZMB)",
}
# extra normalization for checkpoint aliases
CHK_ALIAS = {"havcr2": "tim3", "tim3": "tim3"}


def norm(name):
    n = re.sub(r"[^a-z0-9]", "", name.strip().lower())
    n = CHK_ALIAS.get(n, n)
    return SYN.get(n, n)


def load_moldoveanu():
    p = os.path.join(REPO, "data", "processed", "moldoveanu", "_markers.txt")
    return [l.strip() for l in open(p) if l.strip()]


def load_panel(fn):
    p = os.path.join(REPO, "data", "panels", f"{fn}_panel.tsv")
    names = []
    for line in open(p):
        parts = line.rstrip("\n").split("\t")
        # use the ROWNAME (canonical target symbol, e.g. PD_1/GZMB/CD8a) — the 'name' display
        # column is messier (e.g. IMMUcan lists LAG3 as "LAG3 / LAG33").
        names.append(parts[0])
    return names


# technical / non-antibody channels to exclude from both sides for a fair comparison
TECH = {"dna1", "dna2", "x190bckg", "x191ir", "x193ir", "191ir", "193ir", "iridium"}


def norm_set(markers):
    out = {}
    for m in markers:
        n = norm(m)
        if n in TECH:
            continue
        out[n] = m
    return out


def compare(mold_norm, cand_markers):
    cand = norm_set(cand_markers)
    shared = sorted(set(mold_norm) & set(cand))
    union = sorted(set(mold_norm) | set(cand))
    jac = len(shared) / len(union) * 100
    # checkpoint presence in BOTH
    chk = {}
    for c, disp in CHECKPOINTS.items():
        in_mold = c in mold_norm
        in_cand = c in cand
        chk[disp] = (in_mold, in_cand, in_mold and in_cand)
    n_both = sum(1 for v in chk.values() if v[2])
    return {"shared": [cand[k] if k in cand else k for k in shared], "shared_keys": shared,
            "n_shared": len(shared), "n_union": len(union), "jaccard": jac,
            "checkpoints": chk, "n_checkpoints_both": n_both, "n_cand": len(cand)}


def main():
    mold = load_moldoveanu()
    mold_norm = norm_set(mold)
    candidates = {
        "HochSchulz_2022_Melanoma": "Metastatic melanoma (50 img, 325,881 cells)",
        "IMMUcan_2022_CancerExample": "Primary tumor, immune panel — EXAMPLE/demo subset (14 img, 47,794 cells)",
    }
    results = []
    for fn, desc in candidates.items():
        try:
            r = compare(mold_norm, load_panel(fn))
            r["fn"], r["desc"] = fn, desc
            results.append(r)
        except FileNotFoundError:
            pass
    results.sort(key=lambda r: (r["jaccard"], r["n_checkpoints_both"]), reverse=True)

    best = results[0] if results else None
    clears = bool(best and best["jaccard"] >= THRESHOLD_JACCARD
                  and best["n_checkpoints_both"] >= THRESHOLD_CHECKPOINTS)

    L = []
    A = L.append
    A("# Panel-matched pretraining candidates — go/no-go (Part 1)\n")
    A("_Generated by `src/panel_match_check.py`. Compares candidate imcdatasets marker panels "
      "against the Moldoveanu melanoma panel (same Jaccard method as `docs/marker_overlap.md`)._\n")
    A(f"**Bar to clear:** Jaccard ≥ **{THRESHOLD_JACCARD:.0f}%** (must be an unambiguous "
      f"improvement over the 11.5% Jackson→Moldoveanu overlap, not marginal) AND ≥ "
      f"**{THRESHOLD_CHECKPOINTS}/4** checkpoint/exhaustion markers (PD1, LAG3, TIM3, "
      f"granzyme) shared in **both** panels.\n")
    A(f"Moldoveanu reference panel: {len(mold_norm)} biological markers.\n")

    A("## Ranked candidates\n")
    A("| Rank | Dataset | Jaccard vs Moldoveanu | Shared markers | Checkpoints in both (of 4) | Clears bar? |")
    A("|---|---|---|---|---|---|")
    for i, r in enumerate(results, 1):
        ok = (r["jaccard"] >= THRESHOLD_JACCARD and r["n_checkpoints_both"] >= THRESHOLD_CHECKPOINTS)
        A(f"| {i} | `{r['fn']}` | **{r['jaccard']:.1f}%** ({r['n_shared']}/{r['n_union']}) | "
          f"{r['n_shared']} | {r['n_checkpoints_both']} | {'✅' if ok else '❌'} |")
    A("")

    for r in results:
        A(f"### {r['fn']}")
        A(f"- {r['desc']}")
        A(f"- Jaccard **{r['jaccard']:.1f}%** — shared {r['n_shared']} / union {r['n_union']} "
          f"(candidate panel {r['n_cand']} biological markers).")
        A(f"- Shared proteins: {', '.join('`'+s+'`' for s in r['shared'])}")
        A(f"- Checkpoint/exhaustion markers (present in Moldoveanu | present in candidate | in both):")
        for disp, (im, ic, ib) in r["checkpoints"].items():
            A(f"  - {disp}: {'Y' if im else 'N'} | {'Y' if ic else 'N'} | "
              f"{'**shared**' if ib else 'not shared'}")
        A("")

    A("## Verdict\n")
    if clears:
        A(f"**GO.** Best candidate `{best['fn']}` clears the bar "
          f"(Jaccard {best['jaccard']:.1f}% ≥ {THRESHOLD_JACCARD:.0f}%, "
          f"{best['n_checkpoints_both']}/4 checkpoints). Proceed to Part 2.\n")
    else:
        b = best
        reasons = []
        if b["jaccard"] < THRESHOLD_JACCARD:
            reasons.append(f"best Jaccard {b['jaccard']:.1f}% is below the {THRESHOLD_JACCARD:.0f}% "
                           f"threshold (an improvement over 11.5%, but marginal — the bar was "
                           f"explicitly set to require an unambiguous gain)")
        if b["n_checkpoints_both"] < THRESHOLD_CHECKPOINTS:
            reasons.append(f"only {b['n_checkpoints_both']}/4 checkpoint markers shared in both")
        A(f"**NO-GO — STOP.** No candidate clears the bar. Best is `{b['fn']}` "
          f"({b['jaccard']:.1f}% Jaccard, {b['n_checkpoints_both']}/4 checkpoints): "
          + "; ".join(reasons) + ".\n")
        A("Additional context: the only true melanoma cohort available "
          "(`HochSchulz_2022_Melanoma`) uses a chemokine/mRNA-heavy panel that overlaps the "
          "Moldoveanu immune panel poorly; the checkpoint-rich `IMMUcan_2022_CancerExample` is "
          "a small tutorial/demo subset (14 images, mixed primary tumor, not melanoma) — a poor "
          "pretraining corpus even setting Jaccard aside. Per the pre-registered gate, we do "
          "**not** proceed to Part 2.\n")

    out = os.path.join(REPO, "docs", "panel_matched_candidates.md")
    open(out, "w").write("\n".join(L) + "\n")
    print(f"CLEARS BAR: {clears}")
    for r in results:
        print(f"  {r['fn']}: Jaccard {r['jaccard']:.1f}%  shared {r['n_shared']}  "
              f"checkpoints_both {r['n_checkpoints_both']}/4")
    print("wrote", out)
    return clears


if __name__ == "__main__":
    main()
